version: '3'
services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: backend
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - CASBIN_MODEL_PATH=/pkg/config/model.conf
      - CASBIN_POLICY_PATH=/pkg/config/policy.csv
volumes:
    postgres-data: