database:
  host: database
  port: 5432
  user: postgres
  password: 1
  dbname: task_manager
server:
  host: localhost
  port: 8080
casbin:
  model: pkg/config/model.conf
  policy: pkg/config/policy.csv
jwt:
  signingkey: secret
  expire: 24
  refreshkey: refresh
  rexpire: 24
environment: development
